### ISSUE TITLE
Move to simpler build system

### ISSUE THREAD

**Issue by abdulapopoola** [abdulapopoola/Stream#7]
Change to npm and maybe browserify and remove dependency on grunt

**Comment by isocroft** [comment]
Can you explain this issue further. I presume grunt is a devDependency and not a core dependency.
Plus, *mocha* and *chai* TDD stuff should be devDependencies not core dependencies.

Again, Do you wish to "require()" some other modules in the core stream.js file and use browserify to package the project or you just wish to support browserify build on the client-side by user ??

I ask because the _package.json_ doesn't reference any.

**Comment by abdulapopoola** [comment]
Sure you are right. I would try to clean up stuff and then we would have a roadmap and pick up issues as they come up.
